service: pos-grad

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30
  memorySize: 128
  region: us-east-1
  httpApi:
    authorizers:
      posAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yHEMdh0El
        audience:
          - 2dm057aiuslap1nu6g71a62176
          - 4ubpsra0l516kc2kkskcc9bmh2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:CreateTable
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
        - dynamodb:Scan
      Resource: 'arn:aws:dynamodb:us-east-1:529198180535:table/*'

functions:
  insertGameRating:
    handler: build/functions/insertGameRating.lambdaHandler
    events:
      - httpApi:
          path: /gameRatings
          method: POST
          cors: true
          authorizer:
            name: posAuthorizer
  insertGame:
    handler: build/functions/insertGame.lambdaHandler
    events:
      - httpApi:
          path: /games
          method: POST
          cors: true
          authorizer:
            name: posAuthorizer
  insertGameGenre:
    handler: build/functions/insertGenre.lambdaHandler
    events:
      - httpApi:
          path: /genres
          method: POST
          cors: true
          authorizer:
            name: posAuthorizer
