service: pos-grad

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30
  memorySize: 128
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:CreateTable
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
        - dynamodb:Scan
      Resource: 'arn:aws:dynamodb:us-east-1:529198180535:table/*'

functions:
  insertGameRating:
    handler: build/functions/insertGameRating.lambdaHandler
    events:
      - http:
          path: gameRatings
          method: POST
          cors: true
  insertGame:
    handler: build/functions/insertGame.lambdaHandler
    events:
      - http:
          path: games
          method: POST
          cors: true
  insertGameGenre:
    handler: build/functions/insertGenre.lambdaHandler
    events:
      - http:
          path: genres
          method: POST
          cors: true
